server:
  port: 8082
  address: 0.0.0.0

services:
  weather:
    baseUrl: ${WEATHER_SERVICE_URL:-http://localhost:8080/}
  scheduler-sevice: # update this spelling
    baseUrl: ${SCHEDULER_SERVICE_URL:-http://localhost:8081/}
  resources-sevice: # update this spelling
    baseUrl: ${RESOURCES_SERVICE_URL:-http://localhost:8083/}
